import { useState, useEffect } from "react";
import "../../styles/Master.css"; // Reuse the premium master layouts
import {
    FaBoxOpen, FaEraser, FaSave, FaTimes, FaImage, FaInfoCircle,
    FaIdCard, FaTag, FaSitemap, FaAward, FaBarcode, FaCube,
    FaSlidersH, FaPalette, FaGlasses, FaIndustry, FaMoneyBillWave,
    FaPercentage, FaFileInvoice, FaWarehouse, FaPrint, FaBan, FaUpload
} from "react-icons/fa";

export default function AddProduct() {

    const [product, setProduct] = useState({
        code: "", // Will be auto-generated by backend if left empty
        barcode: "",
        category: "",
        productName: "",
        brand: "",
        model: "",
        modelCode: "",
        colourCode: "",
        colour: "",
        lensColour: "",
        frameType: "",
        madeBy: "",
        power: "",
        cost: "",
        rate: "",
        taxGroup: "",
        hsnCode: "",
        nonStock: false,
        noOfSticker: "",
        initialStock: "" // Only if backend accepts it in product, or just keep it around
    });

    const [options, setOptions] = useState({
        categories: [],
        brands: [],
        models: [],
        colourCodes: [],
        colours: [],
        lensColours: [],
        powers: [],
        frameTypes: [],
        madeBys: [],
        taxGroups: []
    });

    useEffect(() => {
        const fetchOptions = async () => {
            try {
                const endpoints = [
                    { key: 'categories', url: 'category' },
                    { key: 'brands', url: 'brand' },
                    { key: 'models', url: 'model' },
                    { key: 'colourCodes', url: 'colour-code' },
                    { key: 'colours', url: 'colourdetails' },
                    { key: 'lensColours', url: 'lenscolour' },
                    { key: 'powers', url: 'power' },
                    { key: 'frameTypes', url: 'frametype' },
                    { key: 'madeBys', url: 'madeby' },
                    { key: 'taxGroups', url: 'tax-group' }
                ];

                const results = await Promise.all(
                    endpoints.map(ep => fetch(`${import.meta.env.VITE_API_URL}/${ep.url}`).then(res => res.json()).catch(() => []))
                );

                const newOptions = {};
                endpoints.forEach((ep, index) => {
                    newOptions[ep.key] = Array.isArray(results[index]) ? results[index] : [];
                });
                
                setOptions(newOptions);
            } catch (err) {
                console.error("Failed to fetch options", err);
            }
        };
        fetchOptions();
    }, []);

    const [imageFiles, setImageFiles] = useState([]);
    const [imagePreviews, setImagePreviews] = useState([]);

    const handleChange = (e) => {
        const { name, value, type, checked } = e.target;
        setProduct({
            ...product,
            [name]: type === "checkbox" ? checked : value
        });
    };

    const handleImageChange = (e) => {
        const files = Array.from(e.target.files);
        if (files.length > 0) {
            setImageFiles(prev => [...prev, ...files]);
            const newPreviews = files.map(file => URL.createObjectURL(file));
            setImagePreviews(prev => [...prev, ...newPreviews]);
        }
    };

    const handleRemoveImage = (indexToRemove) => {
        setImageFiles(prev => prev.filter((_, idx) => idx !== indexToRemove));
        setImagePreviews(prev => {
            // Revoke object URL to prevent memory leaks
            URL.revokeObjectURL(prev[indexToRemove]);
            return prev.filter((_, idx) => idx !== indexToRemove);
        });
    };

    const handleClear = () => {
        setProduct({
            ...product,
            code: "", barcode: "", category: "", productName: "", brand: "", model: "",
            modelCode: "", colourCode: "",  colour: "", lensColour: "", frameType: "",
            madeBy: "", power: "", cost: "", rate: "", taxGroup: "", hsnCode: "",
            nonStock: false, noOfSticker: "", initialStock: ""
        });
        setImageFiles([]);
        setImagePreviews([]);
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        
        const formData = new FormData();
        
        // Append all text fields
        Object.keys(product).forEach(key => {
            if (product[key] !== "" && product[key] !== null) {
                formData.append(key, product[key]);
            }
        });
        
        // Append images
        if (imageFiles.length < 4) {
            alert("A minimum of 4 photos are required for adding a product. ❌");
            return;
        }

        imageFiles.forEach(file => {
            formData.append("images", file);
        });

        try {
            const res = await fetch(import.meta.env.VITE_API_URL + "/product", {
                method: "POST",
                body: formData
            });

            if (res.ok) {
                const data = await res.json();
                console.log("Product Saved:", data);
                alert("Product Saved Successfully! ✅");
                handleClear();
                // Optionally generate a new code
                setProduct(prev => ({ ...prev, code: "" }));
            } else {
                const errData = await res.json();
                alert(`Failed to save product: ${errData.message || 'Unknown error'}`);
            }
        } catch (error) {
            console.error("Error saving product:", error);
            alert("Error saving product ❌");
        }
    };

    return (
        <div className="master-container" style={{ paddingBottom: '40px' }}>

            <div className="master-header">
                <div className="header-left">
                    <h2><FaBoxOpen /> Add New Product</h2>
                </div>

                <div className="header-buttons">
                    <button className="btn-outline" onClick={handleClear}>
                        <FaTimes /> Cancel
                    </button>
                    <button className="btn-secondary" onClick={handleClear}>
                        <FaEraser /> Clear
                    </button>
                    <button className="btn-primary" onClick={handleSubmit}>
                        <FaSave /> Save Product
                    </button>
                </div>
            </div>

            <div className="master-wrapper">
                
                {/* Visual Image Banner Section */}
                <div className="master-card full-width" style={{ marginBottom: "20px" }}>
                    <div className="card-header">
                        <div className="card-icon">
                            <FaImage />
                        </div>
                        <h3>Product Images</h3>
                    </div>
                    
                    <div className="form-field" style={{ marginBottom: '20px' }}>
                        <label>Upload Gallery (Minimum 4 required) <span style={{color: '#ef4444'}}>*</span></label>
                        <div className="file-upload-wrapper" style={{ position: 'relative', overflow: 'hidden', display: 'inline-block' }}>
                            <button className="btn-secondary" style={{ pointerEvents: 'none' }}>
                                <FaUpload /> Choose Images
                            </button>
                            <input
                                type="file"
                                accept="image/*"
                                multiple
                                onChange={handleImageChange}
                                style={{ position: 'absolute', left: 0, top: 0, opacity: 0, cursor: 'pointer', height: '100%', width: '100%' }}
                            />
                        </div>
                        <p style={{ margin: '8px 0 0 0', fontSize: '0.85rem', color: '#64748b' }}>
                            Upload high quality transparent PNG or JPG images. Max 2MB each. Select multiple files.
                        </p>
                    </div>

                    <div style={{ display: 'flex', gap: '15px', flexWrap: 'wrap' }}>
                        {imagePreviews.length > 0 ? (
                            imagePreviews.map((preview, idx) => (
                                <div key={idx} style={{ position: 'relative', width: '120px', height: '120px' }}>
                                    <img 
                                        src={preview} 
                                        alt={`Preview ${idx + 1}`} 
                                        style={{ width: '100%', height: '100%', objectFit: 'cover', borderRadius: '12px', border: '3px solid rgba(255, 255, 255, 0.8)', boxShadow: '0 4px 15px rgba(0,0,0,0.1)' }} 
                                    />
                                    <button 
                                        type="button"
                                        onClick={() => handleRemoveImage(idx)}
                                        style={{
                                            position: 'absolute',
                                            top: '-8px',
                                            right: '-8px',
                                            background: '#ef4444',
                                            color: 'white',
                                            border: 'none',
                                            borderRadius: '50%',
                                            width: '24px',
                                            height: '24px',
                                            cursor: 'pointer',
                                            fontWeight: 'bold',
                                            display: 'flex',
                                            alignItems: 'center',
                                            justifyContent: 'center',
                                            boxShadow: '0 2px 8px rgba(239, 68, 68, 0.4)'
                                        }}
                                    ><FaTimes size={12} /></button>
                                </div>
                            ))
                        ) : (
                            <div style={{ width: '100%', height: '120px', background: 'rgba(241, 245, 249, 0.5)', display: 'flex', alignItems: 'center', justifyContent: 'center', borderRadius: '12px', border: '2px dashed rgba(148, 163, 184, 0.5)', color: '#64748b' }}>
                                <span>No Images Selected (Min 4 required)</span>
                            </div>
                        )}
                    </div>
                </div>

                {/* Grid Layout for Sections */}
                
                {/* SECTION 1: Basic Details */}
                <div className="master-card" style={{ height: 'fit-content' }}>
                    <div className="card-header">
                        <div className="card-icon"><FaInfoCircle /></div>
                        <h3>Basic Details</h3>
                    </div>
                    <div className="form-grid single-grid">
                        <div className="form-field">
                            <label>Product Code</label>
                            <div className="input-with-icon">
                                <FaIdCard className="input-icon" />
                                <input value={product.code} className="visual-readonly" readOnly placeholder="Auto-generated on save" />
                            </div>
                        </div>
                        
                        <div className="form-field">
                            <label>Product Name <span style={{color: '#ef4444'}}>*</span></label>
                            <div className="input-with-icon">
                                <FaTag className="input-icon" />
                                <input name="productName" value={product.productName} onChange={handleChange} placeholder="Enter full product name" />
                            </div>
                        </div>

                        <div className="form-row" style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '15px' }}>
                            <div className="form-field">
                                <label>Category</label>
                                <div className="input-with-icon">
                                    <FaSitemap className="input-icon" />
                                    <select name="category" value={product.category} onChange={handleChange}>
                                        <option value="">Select Category</option>
                                        {options.categories.map(c => <option key={c.id} value={c.categoryName}>{c.categoryName}</option>)}
                                    </select>
                                </div>
                            </div>
                            <div className="form-field">
                                <label>Brand</label>
                                <div className="input-with-icon">
                                    <FaAward className="input-icon" />
                                    <select name="brand" value={product.brand} onChange={handleChange}>
                                        <option value="">Select Brand</option>
                                        {options.brands.map(b => <option key={b.id} value={b.brandName}>{b.brandName}</option>)}
                                    </select>
                                </div>
                            </div>
                        </div>

                        <div className="form-row" style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '15px' }}>
                            <div className="form-field">
                                <label>Model</label>
                                <div className="input-with-icon">
                                    <FaCube className="input-icon" />
                                    <select name="model" value={product.model} onChange={handleChange}>
                                        <option value="">Select Model</option>
                                        {options.models.map(m => <option key={m.id} value={m.modelName}>{m.modelName}</option>)}
                                    </select>
                                </div>
                            </div>
                            <div className="form-field">
                                <label>Model Code</label>
                                <div className="input-with-icon">
                                    <FaCube className="input-icon" />
                                    <input name="modelCode" value={product.modelCode} onChange={handleChange} placeholder="Model code" />
                                </div>
                            </div>
                        </div>

                        <div className="form-field">
                            <label>Barcode</label>
                            <div className="input-with-icon">
                                <FaBarcode className="input-icon" />
                                <input name="barcode" value={product.barcode} onChange={handleChange} placeholder="Scan, enter, or leave empty to auto-generate" />
                            </div>
                        </div>
                    </div>
                </div>

                {/* SECTION 2: Physical Attributes */}
                <div className="master-card" style={{ height: 'fit-content' }}>
                    <div className="card-header">
                        <div className="card-icon"><FaSlidersH /></div>
                        <h3>Physical Attributes</h3>
                    </div>
                    <div className="form-grid single-grid">
                        <div className="form-row" style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '15px' }}>
                            <div className="form-field">
                                <label>Colour</label>
                                <div className="input-with-icon">
                                    <FaPalette className="input-icon" />
                                    <select name="colour" value={product.colour} onChange={handleChange}>
                                        <option value="">Select Colour</option>
                                        {options.colours.map(c => <option key={c.id} value={c.colourName}>{c.colourName}</option>)}
                                    </select>
                                </div>
                            </div>
                            <div className="form-field">
                                <label>Colour Code</label>
                                <div className="input-with-icon">
                                    <FaPalette className="input-icon" />
                                    <select name="colourCode" value={product.colourCode} onChange={handleChange}>
                                        <option value="">Select Code</option>
                                        {options.colourCodes.map(c => <option key={c.id} value={c.colourCode}>{c.colourCode}</option>)}
                                    </select>
                                </div>
                            </div>
                        </div>
                        
                        <div className="form-row" style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '15px' }}>
                            <div className="form-field">
                                <label>Lens Colour</label>
                                <div className="input-with-icon">
                                    <FaPalette className="input-icon" />
                                    <select name="lensColour" value={product.lensColour} onChange={handleChange}>
                                        <option value="">Select Lens Colour</option>
                                        {options.lensColours.map(c => <option key={c.id} value={c.lensColourName}>{c.lensColourName}</option>)}
                                    </select>
                                </div>
                            </div>
                            <div className="form-field">
                                <label>Power (Sph/Cyl)</label>
                                <div className="input-with-icon">
                                    <FaGlasses className="input-icon" />
                                    <select name="power" value={product.power} onChange={handleChange}>
                                        <option value="">Select Power</option>
                                        {options.powers.map(p => <option key={p.id} value={p.powerName}>{p.powerName}</option>)}
                                    </select>
                                </div>
                            </div>
                        </div>

                        <div className="form-row" style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '15px' }}>
                            <div className="form-field">
                                <label>Frame Type</label>
                                <div className="input-with-icon">
                                    <FaGlasses className="input-icon" />
                                    <select name="frameType" value={product.frameType} onChange={handleChange}>
                                        <option value="">Select Frame Type</option>
                                        {options.frameTypes.map(f => <option key={f.id} value={f.frameTypeName}>{f.frameTypeName}</option>)}
                                    </select>
                                </div>
                            </div>
                            <div className="form-field">
                                <label>Made By</label>
                                <div className="input-with-icon">
                                    <FaIndustry className="input-icon" />
                                    <select name="madeBy" value={product.madeBy} onChange={handleChange}>
                                        <option value="">Select Made By</option>
                                        {options.madeBys.map(m => <option key={m.id} value={m.madeByName}>{m.madeByName}</option>)}
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                {/* SECTION 3: Pricing & Taxes */}
                <div className="master-card" style={{ height: 'fit-content' }}>
                    <div className="card-header">
                        <div className="card-icon"><FaMoneyBillWave /></div>
                        <h3>Pricing & Taxes</h3>
                    </div>
                    <div className="form-grid single-grid">
                        <div className="form-row" style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '15px' }}>
                            <div className="form-field">
                                <label>Cost (Base Price) <span style={{color: '#ef4444'}}>*</span></label>
                                <div className="input-with-icon">
                                    <FaMoneyBillWave className="input-icon" />
                                    <input type="number" min="0" step="0.01" name="cost" value={product.cost} onChange={handleChange} placeholder="0.00" />
                                </div>
                            </div>
                            <div className="form-field">
                                <label>Selling Rate <span style={{color: '#ef4444'}}>*</span></label>
                                <div className="input-with-icon">
                                    <FaMoneyBillWave className="input-icon" />
                                    <input type="number" min="0" step="0.01" name="rate" value={product.rate} onChange={handleChange} placeholder="0.00" />
                                </div>
                            </div>
                        </div>

                        <div className="form-row" style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '15px' }}>
                            <div className="form-field">
                                <label>Tax Group</label>
                                <div className="input-with-icon">
                                    <FaPercentage className="input-icon" />
                                    <select name="taxGroup" value={product.taxGroup} onChange={handleChange}>
                                        <option value="">Select Tax</option>
                                        {options.taxGroups.map(t => <option key={t.id} value={t.taxGroupName}>{t.taxGroupName} ({t.taxPercent}%)</option>)}
                                    </select>
                                </div>
                            </div>
                            <div className="form-field">
                                <label>HSN Code</label>
                                <div className="input-with-icon">
                                    <FaFileInvoice className="input-icon" />
                                    <input name="hsnCode" value={product.hsnCode} onChange={handleChange} placeholder="Enter HSN" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                {/* SECTION 4: Inventory & Extras */}
                <div className="master-card" style={{ height: 'fit-content' }}>
                    <div className="card-header">
                        <div className="card-icon"><FaWarehouse /></div>
                        <h3>Inventory Config</h3>
                    </div>
                    <div className="form-grid single-grid">
                        <div className="form-row" style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '15px' }}>
                            <div className="form-field">
                                <label>Initial Opening Stock</label>
                                <div className="input-with-icon">
                                    <FaWarehouse className="input-icon" />
                                    <input type="number" min="0" name="initialStock" value={product.initialStock} onChange={handleChange} placeholder="0" />
                                </div>
                            </div>
                            <div className="form-field">
                                <label>Print Labels</label>
                                <div className="input-with-icon">
                                    <FaPrint className="input-icon" />
                                    <input type="number" min="0" name="noOfSticker" value={product.noOfSticker} onChange={handleChange} placeholder="0" />
                                </div>
                            </div>
                        </div>

                        <div className="form-field" style={{ background: 'rgba(255,255,255,0.7)', padding: '16px', borderRadius: '12px', border: '1px solid rgba(255,255,255,0.8)' }}>
                            <label style={{ display: 'flex', alignItems: 'center', gap: '10px', margin: 0, cursor: 'pointer', textTransform: 'none' }}>
                                <input
                                    type="checkbox"
                                    name="nonStock"
                                    checked={product.nonStock}
                                    onChange={handleChange}
                                    style={{ width: '20px', height: '20px', margin: 0, accentColor: '#3b82f6' }}
                                />
                                <span style={{ fontWeight: 600, color: '#334155', display: 'flex', alignItems: 'center', gap: '8px' }}>
                                    <FaBan color="#ef4444" /> Non Stock / Service Item
                                </span>
                            </label>
                            <p style={{ margin: '8px 0 0 30px', fontSize: '0.85rem', color: '#64748b' }}>
                                Check this if the item does not require inventory tracking (e.g., eye testing, repair services).
                            </p>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    );
}